apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  replicas: 2  # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: mahammed145/residentialhotelbookingproject  # Image used for containers
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9192  # Port the container is running on

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-service
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9192  # The port the service is running on in the cluster
      targetPort: 9192  # The port exposed by the service
  type: NodePort  # Type of service





